export const MAILS_REQUEST = "MAILS_REQUEST";
export const MAILS_SUCCESS = "MAILS_SUCCESS";
export const MAILS_FAIL = "MAILS_FAIL";

export const USER_MAILS_REQUEST = "USER_MAILS_REQUEST";
export const USER_MAILS_SUCCESS = "USER_MAILS_SUCCESS";
export const USER_MAILS_FAIL = "USER_MAILS_FAIL";

export const SEARCH_MAILS_REQUEST = "SEARCH_MAILS_REQUEST";
export const SEARCH_MAILS_SUCCESS = "SEARCH_MAILS_SUCCESS";
export const SEARCH_MAILS_FAIL = "SEARCH_MAILS_FAIL";
